[package]
name = "program"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.2"
imageproc = "0.25.0"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
sp1-zkvm = "1.1.1"
